### ISSUE TITLE
/media_upload image upload limitations?

### ISSUE THREAD

**Issue by pnt-billy** [DieSocialisten/Walls.io-API-Docs#30]
I'm trying to use the `media_upload` endpoint to upload and image and seem to be running into issues relating to the dimensions of the images.

The documentation states that:
> The maximum file size for uploads is 25MB for images and 50MB for videos.

But my file which is 293k with dimensions of 2048 x 1536, will come back with the this response:
```
<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

The help section of the website states that:
> …you can upload images of almost any size and aspect ratio

If I decrease the resolution of the image to 547 x 410, it will upload successfully.

Should the original image with its original dimensions and size not upload correctly?

**Comment by michaelkamleitner** [comment]
Hi, thanks a lot for getting in touch!
This was in fact an issue on our end - it's fixed now, thanks for reporting!
